spring:
  application:
    name: discodeit

servlet:
  multipart:
    enabled: true
    max-file-size: 5MB
    max-request-size: 20MB

discodeit:
  repository:
    type: jcf   # jcf | file
    file-directory: .discodeit
